<template>
  <section>
    <div class="container">
      <div class="max-width-810">
        <h2 class="h2 h2-indent">Building a new way of shared economy</h2>
      </div>

      <div class="grid-12col-w mt-80">

        <div class="home-s2-span-1">
          <p class="mono-s">read more about rsc labs mission</p>
        </div>

        <div class="home-s2-span-2">
          <p class="body-l">Early adopters, ambassadors, and users hardly get the tiny piece of revenue they deserve for their contributions, as they should, because there is no product without them.</p>
        </div>

        <div class="home-s2-span-3">
          <p class="body-m">Nowadays, most of the income generated by companies and products remains in the hands of the team and a small number of stakeholders. </p>
        </div>

      </div>
    </div>
  </section>
</template>

<script setup lang="ts">



</script>

<style lang="scss">
.home-s2-span-1{
	grid-column: span 1;
  align-self: end;
}

.home-s2-span-2{
  grid-column-start: 4;
  grid-column-end: 6;
}

.home-s2-span-3{
  grid-column-start: 7;
  grid-column-end: 10;
}
</style>
